function(ParseDependTargets depend_targets)
    cmake_parse_arguments(PARSE_ARGV 1 MY "" "" "TARGETS")
    # 递归获取依赖的dll目标
    set(_depends "")
    foreach(_target ${MY_TARGETS})
        get_target_property(_type ${_target} TYPE)
        if(_type STREQUAL "SHARED_LIBRARY")
            list(APPEND _depends "$<TARGET_FILE:${_target}>")
        endif()
        get_target_property(_deps ${_target} INTERFACE_LINK_LIBRARIES)
        if(_deps)
            ParseDependTargets(_child_depends TARGETS ${_deps})
            list(APPEND _depends "${_child_depends}")
        endif()
    endforeach()
    # 去重
    list(REMOVE_DUPLICATES _depends)
    set(${ARGV0} "${_depends}" PARENT_SCOPE)
endfunction()
